### service for welcome 
GET http://localhost:5000/

###

### service , end-point for get an employee record
GET http://localhost:5000/employee

###
GET http://localhost:5000/isemployee

###

GET http://localhost:5000/login

###

POST http://localhost:5000/login
