"""remove eye color from user table

Revision ID: 6c7163ba2012
Revises: 7edeb7c97709
Create Date: 2022-10-08 20:05:56.484271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7163ba2012'
down_revision = '7edeb7c97709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'eye_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('eye_color', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
